# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build_on_win

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    # The type of runner that the job will run on
    runs-on: windows-latest
    if: contains(github.ref, 'refs/tags/v')
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out branch
        uses: actions/checkout@master
        
      - name: Install Node.js, NPM
        uses: actions/setup-node@v1
        with:
          node-version: 14
        
      - name: Build
        run: |
         npm install
         npm run build-publish
      - name: Compress Bundle
        run: |
          npm install -g bestzip
          bestzip Neeto-Vue-win32-x64.zip  dist/electron/Neeto-Vue-win32-x64/*
      - name: Upload Win Package
        uses: actions/upload-artifact@v1
        with:
          name: Windows_Dist
          path: Neeto-Vue-win32-x64.zip
